---
title: "LeafletDallasTransport"
author: "gspinnadauhu"
date: "May 10, 2017"
output: html_document
---

This map shows the public transport stops in the Dallas Area Rapid Transit system.
The data were downloaded on May 10th, 2017 from http://www.dart.org/transitdata/latest/google_transit.zip

Downloading data, unzipping and loading.

```{r}
dir.create("./transitdata")
DART<-"http://www.dart.org/transitdata/latest/google_transit.zip"
download.file(DART,destfile = "./transitdata/google_transit.zip")
unzip(zipfile="./transitdata/google_transit.zip",files="stops.txt",exdir="./transitdata",overwrite=TRUE)
stops<-read.table("./transitdata/stops.txt",sep=",",header=TRUE)
stops$wheelchair_accessible<-as.factor(stops$wheelchair_boarding)
levels(stops$wheelchair_accessible)[1]<-"No"
levels(stops$wheelchair_accessible)[2]<-"Yes"
```

Creating Map
```{r}
library(leaflet)
leaflet(stops) %>% 
        addTiles() %>% 
        addCircleMarkers(~stop_lon,
                         ~stop_lat,
                         popup = ~paste0("Station: ",
                                         as.character(stop_name),
                                         "<BR>Wheelchair Accessible: ",
                                         as.character(wheelchair_accessible)),
                         clusterOptions=markerClusterOptions())
```